### PR TITLE
config: add support for signet

### LINKED ISSUE #80: Signet support
Tried to setup lndmon with a custom signet, but was informatic by the error message that signet is not yet supported.

### PR DESCRIPTION
**Pull request by mrfelton**
Is there anything more than this needed to enable signet support?

Fixes #80

### CODE REVIEW

**Comment by samfeder** [comment]
Bump on this. Anything else needed?

**Comment by guggero** [comment]
Oh, I think this fell below the radar because it looked like a duplicate of https://github.com/lightninglabs/faraday/pull/193 when I looked at my daily notifications.
Sorry about that, will put it in my review queue now.

@samfeder you're welcome to test and review as well to move along faster.

**Review by guggero — APPROVED** [review]
LGTM :tada: 

Confirmed that the `lndclient` version is up to date and should handle all the `lnd` connection related part of signet support.

**Review by Roasbeef — APPROVED** [review]
LGTM 🦄

**Pull request merged**
