### PR TITLE
maintenance: Bump lnd and lndclient versions, use dockerized linter and formatter, use Golang 1.18

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/lndmon/issues/82.

### CODE REVIEW

**Review by sputn1ck — CHANGES_REQUESTED** [review]
TACK!

Fixing the whitespace complain made the linter run through fine

**Comment by guggero** [comment]
Fixed the linter issues.

**Review by sputn1ck — APPROVED** [review]
LGTM

**Comment by thinkmassive** [comment]
tACK, LGTM too!

We haven't tagged a release in a long time. Could we tag this as `v0.2.1`?

**Pull request merged**
