### PR TITLE
config: add --disablegraph

### PR DESCRIPTION
**Pull request by joostjager**
`lndmon` is known (reported by multiple users) to cause high cpu load problems for lnd. This is cause by the `DescribeGraph` call which is really too heavy for frequent scraping.

This PR adds a command line flag to disable the graph metrics.

### CODE REVIEW

**Comment by joostjager** [comment]
@carlaKC how about this one? I believe almost every user of lndmon has run into this

**Review by carlaKC — APPROVED** [review]
Out of curiosity, what hardware are you running on where you get issues with graph metrics? 

I think this is worth adding, because we're likely not going to get around to streamlining the graph metrics with high prio.

**Comment by joostjager** [comment]
It is running on a dual-core VM. But I don't think that a full graph fetch at a typical scrape interval is ever going to work.

**Comment by carlaKC** [comment]
> But I don't think that a full graph fetch at a typical scrape interval is ever going to work.

Yeah, definitely not ideal to poll the whole graph. Would be great to move a few of the metrics over to subscriptions, but it's difficult to find the time when it's _mostly_ working.

**Pull request merged**
